### ISSUE TITLE
Profane inside word

### ISSUE THREAD

**Issue by johnroper100** [areebbeigh/profanityfilter#16]
Hi, I'd like to use this to check if usernames include profane words, however, usernames are all one word and is_profane isn't able to pick up profane words when they are connected to other words. Can you add support for this? For example, if an inputted username is `f***youusername` it should mark as profane.

**Comment by areebbeigh** [comment]
Noted. Thanks.

**Comment by areebbeigh** [comment]
Implemented. [0de9956](https://github.com/areebbeigh/profanityfilter/commit/0de9956227ac9cb26353ee14d57f9c4059e49152)

Refer to [Word Boundaries](https://areebbeigh.github.io/profanityfilter/#words-boundaries) in the docs.

**Comment by johnroper100** [comment]
Thanks!

**Comment by johnroper100** [comment]
This doesn't seem to apply to is_clean

**Comment by areebbeigh** [comment]
Could you provide the sample code? Because is_clean is passing in https://github.com/areebbeigh/profanityfilter/blob/master/tests/test_profanity_noboundries.py

**Comment by johnroper100** [comment]
Sorry, my mistake, I was testing without boundries turned off.
