### ISSUE TITLE
Rework

### ISSUE THREAD

**Issue by sarahsturgeon** [areebbeigh/profanityfilter#2]
Hey @areebbeigh I was intending on just adding pluralization support, but I ended up reworking a lot of the logic. I won't make a PR until we have a chance to chat (and until I get it ironed out).

I converted the plugin to a class structure, so ideally you could do:
```python
pf = ProfanityFilter()
pf.append_words(['more', 'profane', 'words'])

print pf.censor('some of these words are fucking profane')
```
`>some of these ***** are ******* *******`

Take a look at the changes I made in this commit (I didn't do it atomically because I wasn't expecting to do so much! I got caught up in it.): https://github.com/brandonsturgeon/profanityfilter/commit/8e34e92b3e69f3d59e161f5a3c1cc098ea6371b3

**Comment by areebbeigh** [comment]
Hi @brandonsturgeon I see you've made a lot of improvements. This is really great! Thanks! I request you to go ahead and finish up with the final touches, I'll be waiting for the final PR!

**Comment by sarahsturgeon** [comment]
Sorry, as is typical of me, I sort of forgot about this. I'll add it to my list again :)

I don't think I could bring it all the way across the finish line, but I could get it to a mostly-working state and send you a pull request. What do you think about that?

**Comment by areebbeigh** [comment]
Hi.

Yeah that's cool. I'm caught up in exams and stuff right now, I'll work on
the rest after I'm done :). Thanks.

*grew a neck beard* "Still waiting for your PR"

(I didn't really grow a neck beard).

**Comment by sarahsturgeon** [comment]
Haha :)

I made the PR
