### ISSUE TITLE
Project abandoned? 

### ISSUE THREAD

**Issue by duttonw** [areebbeigh/profanityfilter#27]
Hi @areebbeigh ,

Have you abandoned this project, last release in 2018.

My team under qld-gov-au org is using this python plugin and would like to keep it maintained. 

Are you able to provide myself @duttonw and @ThrawnCA admin rights to this project as well as maintainer access to  https://pypi.org/project/profanityfilter/ (username: duttonwz ) . 

With that I can build out the GitHub Actions CICD pipline to allow auto version deployment to pypi as well as incorporate our downstream 'fixes' we have open on https://github.com/areebbeigh/profanityfilter/pull/26

**Comment by areebbeigh** [comment]
Hey. Yes, I haven't been able to keep up with maintenance because of time constraints and more so because there seem to be better alternatives available.

I don't mind handing over the project's maintenance if it helps current users. I will be adding you as a maintainer to the repository here and on PyPI.

**Comment by duttonw** [comment]
Hi @areebbeigh ,

Can you enable 'pages' under [settings ](https://github.com/areebbeigh/profanityfilter/settings/pages) "source" be ``GitHub Actions``. then under [environment](https://github.com/areebbeigh/profanityfilter/settings/environments), for 'environment'  ``github-pages`` update the 'Deployment branches and tags' to allow ``develop``,  ``master`` and  ``main``. 

This will then create the doc's like https://duttonw.github.io/profanityfilter/

**Comment by duttonw** [comment]
CICD for auto pypi deployments is now configured and i've cut 2.1.0 from the work @ThrawnCA  did on our fork.

https://github.com/areebbeigh/profanityfilter/actions/runs/12019968973
https://pypi.org/project/profanityfilter/2.1.0/

This should make it easier to support going forward.

**Comment by duttonw** [comment]
Just ran the doc's action and its all happy.
https://github.com/areebbeigh/profanityfilter/actions/runs/12059353024

site: https://areebbeigh.github.io/profanityfilter/
will be kepted up to date on branch update.

**Comment by ThrawnCA** [comment]
@areebbeigh Which alternatives did you mean? https://pypi.org/project/profanity-filter/ is also unmaintained and its repository https://github.com/rominf/profanity-filter is archived.
