### ISSUE TITLE
Remove a word?

### ISSUE THREAD

**Issue by jacebrowning** [areebbeigh/profanityfilter#3]
Is there any way to remove a word from the list of bad words? For example, in my application that generates memes, I don't want to block "damn" because it's a key word in several memes.

**Comment by areebbeigh** [comment]
Not yet. I'll add it ASAP. I guess till then you could define a custom list of bad words by removing the acceptable words from get_bad_words()?

**Comment by ali1234** [comment]
Likewise, I want to remove "screw" from the list, because I'm using this in a techy channel, people talk abut screws and nuts and bolts all the time. :)

**Comment by areebbeigh** [comment]
Although super late, this method has been added. Thanks.

https://github.com/areebbeigh/profanityfilter/commit/cdefbd2a3e9b961dd89b613f4530e04679f54288#diff-f8cb42dd5dae1ed599eb293175338441
